source 'https://rubygems.org'

gem 'rails', '~> 4.2.3'
gem 'mysql2', '~> 0.3.18'

gem 'sass-rails'
gem 'uglifier'
gem 'coffee-rails'
gem 'jquery-rails'
gem 'turbolinks'

gem 'aws-sdk', '~> 2'

gem 'faraday_middleware'

gem 'console_candy', github: 'etcetc/console_candy'
gem 'npb_notification', github: 'etcetc/npb_notification'
gem 'enum_handler', github: 'asux/enum_handler'

gem 'gcm'
gem 'houston'
gem 'twilio-ruby'
gem 'global_phone'

gem 'pry-rails'
gem 'figaro', github: 'asux/figaro', branch: 'feature/eb-set-command'
gem 'awesome_print'
gem 'slim-rails'

gem 'bootstrap-sass'
gem 'simple_form'

gem 'settingslogic'
gem 'rack-attack'
gem 'newrelic_rpm'
gem 'kaminari'
gem 'aasm'
gem 'activerecord-colored_log_subscriber'
gem 'active_interaction', '~> 3.0'

gem 'remote_syslog_logger'
gem 'rollbar'

group :development do
  gem 'better_errors'
  gem 'binding_of_caller'
  gem 'guard'
  gem 'guard-bundler', require: false
  gem 'guard-pow', require: false
  gem 'guard-rspec', require: false
  gem 'guard-zeus'
  gem 'guard-migrate'
  gem 'guard-rubocop'
  gem 'terminal-notifier-guard'
  gem 'quiet_assets'
  gem 'rb-fchange', require: false
  gem 'rb-fsevent', require: false
  gem 'rb-inotify', require: false
  gem 'rails_layout'
  gem 'derailed_benchmarks'
end

group :development, :test do
  gem 'pry-rescue'
  gem 'pry-remote'
  gem 'pry-byebug'
  gem 'rspec-rails'
  gem 'factory_girl_rails'
  gem 'jazz_fingers'
  gem 'fuubar'
end

group :test do
  gem 'database_cleaner'
  gem 'faker'
  gem 'capybara'
  gem 'launchy'
  gem 'shoulda-matchers', '~> 2.8'
  gem 'simplecov', require: false
  gem 'webmock'
  gem 'vcr'
  gem 'timecop'
  gem 'json_spec'
end
